apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:24Z
    labels:
      app: cortical-voluba-celery
    name: cortical-voluba-celery
    namespace: cortical-voluba
    selfLink: /apis/image.openshift.io/v1/namespaces/cortical-voluba/imagestreams/cortical-voluba-celery
    uid: 3bb4af1e-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:24Z
    labels:
      app: cortical-voluba-flask
    name: cortical-voluba-flask
    namespace: cortical-voluba
    selfLink: /apis/image.openshift.io/v1/namespaces/cortical-voluba/imagestreams/cortical-voluba-flask
    uid: 3bbbff32-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:24Z
    labels:
      app: cortical-voluba-celery
    name: cortical-voluba-celery
    namespace: cortical-voluba
    selfLink: /apis/build.openshift.io/v1/namespaces/cortical-voluba/buildconfigs/cortical-voluba-celery
    uid: 3bc3d7fc-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: cortical-voluba-celery:latest
    postCommit:
      script: |
        set -e
        # Without PIP_IGNORE_INSTALLED=0 the Debian version of pip would
        # re-install all dependencies in the user's home directory
        # (https://github.com/pypa/pip/issues/4222#issuecomment-417672236)
        PIP_IGNORE_INSTALLED=0 python3 -m pip install --user /source[tests]
        cd /source
        python3 -m pytest tests/
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: dev
        uri: https://github.com/HumanBrainProject/cortical-voluba.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.celery
        forcePull: true
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secretReference:
          name: github-webhook-secret
      type: GitHub
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:24Z
    labels:
      app: cortical-voluba-flask
    name: cortical-voluba-flask
    namespace: cortical-voluba
    selfLink: /apis/build.openshift.io/v1/namespaces/cortical-voluba/buildconfigs/cortical-voluba-flask
    uid: 3bcbaffb-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: cortical-voluba-flask:latest
    postCommit:
      script: |
        set -e
        # Without PIP_IGNORE_INSTALLED=0 the Debian version of pip would
        # re-install all dependencies in the user's home directory
        # (https://github.com/pypa/pip/issues/4222#issuecomment-417672236)
        PIP_IGNORE_INSTALLED=0 python3 -m pip install --user /source[tests]
        cd /source
        python3 -m pytest tests/
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: dev
        uri: https://github.com/HumanBrainProject/cortical-voluba.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.flask
        forcePull: true
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - github:
        secretReference:
          name: github-webhook-secret
      type: GitHub
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:24Z
    labels:
      app: cortical-voluba-celery
    name: cortical-voluba-celery
    namespace: cortical-voluba
    selfLink: /apis/apps.openshift.io/v1/namespaces/cortical-voluba/deploymentconfigs/cortical-voluba-celery
    uid: 3bd3b7ae-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: cortical-voluba-celery
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cortical-voluba-celery
          deploymentconfig: cortical-voluba-celery
      spec:
        containers:
        - env:
          - name: INSTANCE_PATH
            value: /instance
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: redis
          image: docker-registry.default.svc:5000/cortical-voluba/cortical-voluba-celery
          imagePullPolicy: Always
          name: cortical-voluba-celery
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /instance
            name: volume-tua14
          - mountPath: /static-data
            name: static-data
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: instance-dir
          name: volume-tua14
        - name: static-data
          persistentVolumeClaim:
            claimName: static-data
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cortical-voluba-celery
        from:
          kind: ImageStreamTag
          name: cortical-voluba-celery:latest
          namespace: cortical-voluba
        lastTriggeredImage: docker-registry.default.svc:5000/cortical-voluba/cortical-voluba-celery
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:24Z
    labels:
      app: cortical-voluba-flask
    name: cortical-voluba-flask
    namespace: cortical-voluba
    selfLink: /apis/apps.openshift.io/v1/namespaces/cortical-voluba/deploymentconfigs/cortical-voluba-flask
    uid: 3bdb1451-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: cortical-voluba-flask
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cortical-voluba-flask
          deploymentconfig: cortical-voluba-flask
      spec:
        containers:
        - env:
          - name: INSTANCE_PATH
            value: /instance
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: redis
          image: docker-registry.default.svc:5000/cortical-voluba/cortical-voluba-flask
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: cortical-voluba-flask
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /instance
            name: volume-0dl4t
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: instance-dir
          name: volume-0dl4t
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cortical-voluba-flask
        from:
          kind: ImageStreamTag
          name: cortical-voluba-flask:latest
          namespace: cortical-voluba
        lastTriggeredImage: docker-registry.default.svc:5000/cortical-voluba/cortical-voluba-flask
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    creationTimestamp: 2020-01-29T14:11:25Z
    labels:
      template: redis-ephemeral-template
      template.openshift.io/template-instance-owner: 6854f2e8-d472-11e9-94ad-fa163e2c730e
    name: redis
    namespace: cortical-voluba
    selfLink: /apis/apps.openshift.io/v1/namespaces/cortical-voluba/deploymentconfigs/redis
    uid: 3be260e7-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: redis
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: redis
      spec:
        containers:
        - env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: redis
          image: docker-registry.default.svc:5000/openshift/redis@sha256:06dbb609484330ec6be6090109f1fa16e936afcf975d1cbc5fff3e6c7cae7542
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - test "$(redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD ping)" == "PONG"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/redis/data
            name: redis-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: redis-data
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:3.2
          namespace: openshift
        lastTriggeredImage: docker-registry.default.svc:5000/openshift/redis@sha256:06dbb609484330ec6be6090109f1fa16e936afcf975d1cbc5fff3e6c7cae7542
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:25Z
    labels:
      app: cortical-voluba-celery
    name: cortical-voluba-celery
    namespace: cortical-voluba
    selfLink: /api/v1/namespaces/cortical-voluba/services/cortical-voluba-celery
    uid: 3bea817d-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    clusterIP: 172.30.188.203
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: cortical-voluba-celery
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: 2020-01-29T14:11:25Z
    labels:
      app: cortical-voluba-flask
    name: cortical-voluba-flask
    namespace: cortical-voluba
    selfLink: /api/v1/namespaces/cortical-voluba/services/cortical-voluba-flask
    uid: 3bf3630b-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    clusterIP: 172.30.53.10
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: cortical-voluba-flask
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: redis://{.spec.clusterIP}:{.spec.ports[?(.name=="redis")].port}
    creationTimestamp: 2020-01-29T14:11:25Z
    labels:
      template: redis-ephemeral-template
      template.openshift.io/template-instance-owner: 6854f2e8-d472-11e9-94ad-fa163e2c730e
    name: redis
    namespace: cortical-voluba
    selfLink: /api/v1/namespaces/cortical-voluba/services/redis
    uid: 3c0db02b-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    clusterIP: 172.30.26.169
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: redis
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: 2020-01-29T14:11:25Z
    labels:
      app: cortical-voluba-flask
    name: cortical-voluba-https
    namespace: cortical-voluba
    selfLink: /apis/route.openshift.io/v1/namespaces/cortical-voluba/routes/cortical-voluba-https
    uid: 3c164cb5-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    host: cortical-voluba.apps-dev.hbp.eu
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: cortical-voluba-flask
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: 2020-01-29T14:20:48Z
    name: static-data
    namespace: cortical-voluba
    selfLink: /api/v1/namespaces/cortical-voluba/persistentvolumeclaims/static-data
    uid: 8bb44566-42a2-11ea-bfa5-fa163e0fc7ce
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  data:
    config.py: |
      import os
      CELERY_BROKER_URL = 'redis://:' + os.environ['REDIS_PASSWORD'] + '@redis:6379/0'
      CELERY_RESULT_BACKEND = CELERY_BROKER_URL
      CORS_ORIGINS = r'https://voluba(-dev)?\.apps(-dev)?\.hbp\.eu'
      PROXY_FIX = {
          'x_for': 1,
          'x_host': 1,
          'x_port': 1,
          'x_proto': 1,
      }
      TEMPLATE_EQUIVOLUMETRIC_DEPTH = '/static-data/BigBrain_equivolumetric_depth.nii.gz'
      ROOT_REDIRECT = 'https://voluba-dev.apps-dev.hbp.eu/'
  kind: ConfigMap
  metadata:
    creationTimestamp: 2020-01-29T14:11:25Z
    name: instance-dir
    namespace: cortical-voluba
    selfLink: /api/v1/namespaces/cortical-voluba/configmaps/instance-dir
    uid: 3c29fbb5-42a1-11ea-bfa5-fa163e0fc7ce
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2020-01-29T14:11:25Z
    labels:
      app: cortical-voluba-celery
    name: cortical-voluba-celery
    namespace: cortical-voluba
    selfLink: /apis/autoscaling/v1/namespaces/cortical-voluba/horizontalpodautoscalers/cortical-voluba-celery
    uid: 3c328384-42a1-11ea-bfa5-fa163e0fc7ce
  spec:
    maxReplicas: 5
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: cortical-voluba-celery
    targetCPUUtilizationPercentage: 50
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
